### ISSUE TITLE
Multiple upload?

### ISSUE THREAD

**Issue by mesaglam** [BunnyWay/BunnyCDN.PHP.Storage#4]
Isn't there any way to upload multiple files at once?

**Comment by rafael-at-bunny** [comment]
If you are looking into _parallel_ uploads, you can use [GuzzleHttp\Promise](https://github.com/guzzle/promises) (which since 2.1.0 this library depends on).

Example:

```php
$promises = [];
foreach ($files_to_upload as $local_path => $remote_path) {
    $promise = new \GuzzleHttp\Promise\Promise(
        function () use (&$promise, $storage, $local_path, $remote_path) {
            /** @var \GuzzleHttp\Promise\Promise $promise */
            $promise->resolve($storage->upload($local_path, $remote_path));
        }
    );

    $promises[$remote_path] = $promise;
    unset($promise);
}

\GuzzleHttp\Promise\Utils::unwrap($promises);
```

If you are looking into passing a directory/array of files to the `upload()` method, that unfortunately isn't possible at the moment.

**Comment by coffebar** [comment]
What about [Concurrent Connections Per IP](https://docs.bunny.net/reference/edge-storage-api-limits) and _Concurrent Uploads Per Storage Zone_? Should not this script to be limited to 50 parallel uploads?

**Comment by rafael-at-bunny** [comment]
You can use https://docs.guzzlephp.org/en/stable/quickstart.html#concurrent-requests to limit the amount of concurrent requests.
